spring.application.name=library-2026

server.port=8080

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=YOUR_USERNAME_HERE
spring.datasource.password=YOUR_PASSWORD_HERE
spring.datasource.url=jdbc:mysql://localhost:3306/library-2026

spring.jpa.open-in-view=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.freemarker.suffix=.ftl

