create table authors (date_of_birth datetime(6), id bigint not null auto_increment, biography varchar(255), first_name varchar(255), image varchar(255), last_name varchar(255), primary key (id)) engine=InnoDB;
create table categories (id bigint not null auto_increment, description varchar(255), image varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table genres (id bigint not null auto_increment, name varchar(255), primary key (id)) engine=InnoDB;
create table publication_instances (id bigint not null auto_increment, publication_id bigint, book_condition varchar(255), inventory_number varchar(255), location varchar(255), status varchar(255), primary key (id)) engine=InnoDB;
create table publications (number_of_pages integer not null, category_id bigint, id bigint not null auto_increment, publication_date datetime(6), publisher_id bigint, image varchar(255), isbn varchar(255), language varchar(255), summary varchar(255), title varchar(255), primary key (id)) engine=InnoDB;
create table publications_authors (authors_id bigint not null, publications_id bigint not null, primary key (authors_id, publications_id)) engine=InnoDB;
create table publications_genres (genres_id bigint not null, publications_id bigint not null, primary key (genres_id, publications_id)) engine=InnoDB;
create table publishers (id bigint not null auto_increment, address varchar(255), description varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table readers (balance float(53) not null, id bigint not null, opened_date datetime(6), library_card_number varchar(255), primary key (id)) engine=InnoDB;
create table reservations (due_date datetime(6), id bigint not null auto_increment, issue_date datetime(6), publication_instance_id bigint, reader_id bigint, reservation_date datetime(6), return_date datetime(6), pick_up_method varchar(255), status varchar(255), primary key (id)) engine=InnoDB;
create table roles (id bigint not null auto_increment, role_name varchar(255), primary key (id)) engine=InnoDB;
create table users (is_active bit not null, created_date datetime(6), date_of_birth datetime(6), id bigint not null auto_increment, username varchar(50), email varchar(255), first_name varchar(255), image varchar(255), last_name varchar(255), password varchar(255), phone_number varchar(255), primary key (id)) engine=InnoDB;
create table users_roles (roles_id bigint not null, users_id bigint not null, primary key (roles_id, users_id)) engine=InnoDB;
alter table publication_instances add constraint FKeqem9eu60q0ev1a3mu1936wcy foreign key (publication_id) references publications (id);
alter table publications add constraint FK75xnhl48vv4ma0gh4e49es8ji foreign key (category_id) references categories (id);
alter table publications add constraint FK89stuhio56j0ohtrwfpvf1pl foreign key (publisher_id) references publishers (id);
alter table publications_authors add constraint FKb7hvcbwic2o3rb36h0bvqreoe foreign key (authors_id) references authors (id);
alter table publications_authors add constraint FKmux26nsq585uydqojhaifhkj6 foreign key (publications_id) references publications (id);
alter table publications_genres add constraint FKgo7cknc1jw7bbn63ooigm71bx foreign key (genres_id) references genres (id);
alter table publications_genres add constraint FKmehqavt1nmpq6hgfry0eb0rvk foreign key (publications_id) references publications (id);
alter table readers add constraint FKn5kenaimh48xi6df3d1p1ewa1 foreign key (id) references users (id);
alter table reservations add constraint FKgi0q1tvunr72w4gjbtb2qi9ht foreign key (publication_instance_id) references publication_instances (id);
alter table reservations add constraint FKbie5krb0yu650ye59ecc6647f foreign key (reader_id) references readers (id);
alter table users_roles add constraint FKa62j07k5mhgifpp955h37ponj foreign key (roles_id) references roles (id);
alter table users_roles add constraint FKml90kef4w2jy7oxyqv742tsfc foreign key (users_id) references users (id);
